#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend aabdul
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 136082-web-01 54.209.183.230:80 check
    server 136082-web-02 34.203.75.80:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
